// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: engine.proto

package engine

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Runtime_GetStatus_FullMethodName       = "/engine.Runtime/GetStatus"
	Runtime_ListModels_FullMethodName      = "/engine.Runtime/ListModels"
	Runtime_LoadModel_FullMethodName       = "/engine.Runtime/LoadModel"
	Runtime_UnloadModel_FullMethodName     = "/engine.Runtime/UnloadModel"
	Runtime_StreamInference_FullMethodName = "/engine.Runtime/StreamInference"
)

// RuntimeClient is the client API for Runtime service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RuntimeClient interface {
	GetStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RuntimeStatus, error)
	ListModels(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ModelList, error)
	LoadModel(ctx context.Context, in *LoadModelRequest, opts ...grpc.CallOption) (*ModelInfo, error)
	UnloadModel(ctx context.Context, in *UnloadModelRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	StreamInference(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[InferenceRequest, InferenceResponse], error)
}

type runtimeClient struct {
	cc grpc.ClientConnInterface
}

func NewRuntimeClient(cc grpc.ClientConnInterface) RuntimeClient {
	return &runtimeClient{cc}
}

func (c *runtimeClient) GetStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RuntimeStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimeStatus)
	err := c.cc.Invoke(ctx, Runtime_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) ListModels(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ModelList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelList)
	err := c.cc.Invoke(ctx, Runtime_ListModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) LoadModel(ctx context.Context, in *LoadModelRequest, opts ...grpc.CallOption) (*ModelInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelInfo)
	err := c.cc.Invoke(ctx, Runtime_LoadModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) UnloadModel(ctx context.Context, in *UnloadModelRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Runtime_UnloadModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) StreamInference(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[InferenceRequest, InferenceResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Runtime_ServiceDesc.Streams[0], Runtime_StreamInference_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[InferenceRequest, InferenceResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Runtime_StreamInferenceClient = grpc.BidiStreamingClient[InferenceRequest, InferenceResponse]

// RuntimeServer is the server API for Runtime service.
// All implementations must embed UnimplementedRuntimeServer
// for forward compatibility.
type RuntimeServer interface {
	GetStatus(context.Context, *emptypb.Empty) (*RuntimeStatus, error)
	ListModels(context.Context, *emptypb.Empty) (*ModelList, error)
	LoadModel(context.Context, *LoadModelRequest) (*ModelInfo, error)
	UnloadModel(context.Context, *UnloadModelRequest) (*emptypb.Empty, error)
	StreamInference(grpc.BidiStreamingServer[InferenceRequest, InferenceResponse]) error
	mustEmbedUnimplementedRuntimeServer()
}

// UnimplementedRuntimeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRuntimeServer struct{}

func (UnimplementedRuntimeServer) GetStatus(context.Context, *emptypb.Empty) (*RuntimeStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedRuntimeServer) ListModels(context.Context, *emptypb.Empty) (*ModelList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListModels not implemented")
}
func (UnimplementedRuntimeServer) LoadModel(context.Context, *LoadModelRequest) (*ModelInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method LoadModel not implemented")
}
func (UnimplementedRuntimeServer) UnloadModel(context.Context, *UnloadModelRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UnloadModel not implemented")
}
func (UnimplementedRuntimeServer) StreamInference(grpc.BidiStreamingServer[InferenceRequest, InferenceResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamInference not implemented")
}
func (UnimplementedRuntimeServer) mustEmbedUnimplementedRuntimeServer() {}
func (UnimplementedRuntimeServer) testEmbeddedByValue()                 {}

// UnsafeRuntimeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RuntimeServer will
// result in compilation errors.
type UnsafeRuntimeServer interface {
	mustEmbedUnimplementedRuntimeServer()
}

func RegisterRuntimeServer(s grpc.ServiceRegistrar, srv RuntimeServer) {
	// If the following call panics, it indicates UnimplementedRuntimeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Runtime_ServiceDesc, srv)
}

func _Runtime_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).GetStatus(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_ListModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).ListModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_ListModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).ListModels(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_LoadModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).LoadModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_LoadModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).LoadModel(ctx, req.(*LoadModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_UnloadModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnloadModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).UnloadModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_UnloadModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).UnloadModel(ctx, req.(*UnloadModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_StreamInference_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RuntimeServer).StreamInference(&grpc.GenericServerStream[InferenceRequest, InferenceResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Runtime_StreamInferenceServer = grpc.BidiStreamingServer[InferenceRequest, InferenceResponse]

// Runtime_ServiceDesc is the grpc.ServiceDesc for Runtime service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Runtime_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "engine.Runtime",
	HandlerType: (*RuntimeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _Runtime_GetStatus_Handler,
		},
		{
			MethodName: "ListModels",
			Handler:    _Runtime_ListModels_Handler,
		},
		{
			MethodName: "LoadModel",
			Handler:    _Runtime_LoadModel_Handler,
		},
		{
			MethodName: "UnloadModel",
			Handler:    _Runtime_UnloadModel_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamInference",
			Handler:       _Runtime_StreamInference_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "engine.proto",
}

const (
	Rag_UpsertDocument_FullMethodName = "/engine.Rag/UpsertDocument"
	Rag_DeleteDocument_FullMethodName = "/engine.Rag/DeleteDocument"
	Rag_Search_FullMethodName         = "/engine.Rag/Search"
	Rag_GetRagStatus_FullMethodName   = "/engine.Rag/GetRagStatus"
	Rag_ListDocuments_FullMethodName  = "/engine.Rag/ListDocuments"
)

// RagClient is the client API for Rag service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RagClient interface {
	UpsertDocument(ctx context.Context, in *UpsertRequest, opts ...grpc.CallOption) (*UpsertResponse, error)
	DeleteDocument(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	GetRagStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RagStatus, error)
	ListDocuments(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DocumentList, error)
}

type ragClient struct {
	cc grpc.ClientConnInterface
}

func NewRagClient(cc grpc.ClientConnInterface) RagClient {
	return &ragClient{cc}
}

func (c *ragClient) UpsertDocument(ctx context.Context, in *UpsertRequest, opts ...grpc.CallOption) (*UpsertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertResponse)
	err := c.cc.Invoke(ctx, Rag_UpsertDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragClient) DeleteDocument(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Rag_DeleteDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, Rag_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragClient) GetRagStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RagStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RagStatus)
	err := c.cc.Invoke(ctx, Rag_GetRagStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragClient) ListDocuments(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DocumentList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DocumentList)
	err := c.cc.Invoke(ctx, Rag_ListDocuments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RagServer is the server API for Rag service.
// All implementations must embed UnimplementedRagServer
// for forward compatibility.
type RagServer interface {
	UpsertDocument(context.Context, *UpsertRequest) (*UpsertResponse, error)
	DeleteDocument(context.Context, *DeleteRequest) (*emptypb.Empty, error)
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	GetRagStatus(context.Context, *emptypb.Empty) (*RagStatus, error)
	ListDocuments(context.Context, *emptypb.Empty) (*DocumentList, error)
	mustEmbedUnimplementedRagServer()
}

// UnimplementedRagServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRagServer struct{}

func (UnimplementedRagServer) UpsertDocument(context.Context, *UpsertRequest) (*UpsertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertDocument not implemented")
}
func (UnimplementedRagServer) DeleteDocument(context.Context, *DeleteRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDocument not implemented")
}
func (UnimplementedRagServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedRagServer) GetRagStatus(context.Context, *emptypb.Empty) (*RagStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRagStatus not implemented")
}
func (UnimplementedRagServer) ListDocuments(context.Context, *emptypb.Empty) (*DocumentList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDocuments not implemented")
}
func (UnimplementedRagServer) mustEmbedUnimplementedRagServer() {}
func (UnimplementedRagServer) testEmbeddedByValue()             {}

// UnsafeRagServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RagServer will
// result in compilation errors.
type UnsafeRagServer interface {
	mustEmbedUnimplementedRagServer()
}

func RegisterRagServer(s grpc.ServiceRegistrar, srv RagServer) {
	// If the following call panics, it indicates UnimplementedRagServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Rag_ServiceDesc, srv)
}

func _Rag_UpsertDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServer).UpsertDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rag_UpsertDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServer).UpsertDocument(ctx, req.(*UpsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rag_DeleteDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServer).DeleteDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rag_DeleteDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServer).DeleteDocument(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rag_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rag_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rag_GetRagStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServer).GetRagStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rag_GetRagStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServer).GetRagStatus(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rag_ListDocuments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServer).ListDocuments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rag_ListDocuments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServer).ListDocuments(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Rag_ServiceDesc is the grpc.ServiceDesc for Rag service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Rag_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "engine.Rag",
	HandlerType: (*RagServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpsertDocument",
			Handler:    _Rag_UpsertDocument_Handler,
		},
		{
			MethodName: "DeleteDocument",
			Handler:    _Rag_DeleteDocument_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _Rag_Search_Handler,
		},
		{
			MethodName: "GetRagStatus",
			Handler:    _Rag_GetRagStatus_Handler,
		},
		{
			MethodName: "ListDocuments",
			Handler:    _Rag_ListDocuments_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "engine.proto",
}

const (
	Context_GetContextStatus_FullMethodName = "/engine.Context/GetContextStatus"
	Context_ListResources_FullMethodName    = "/engine.Context/ListResources"
	Context_UpsertResource_FullMethodName   = "/engine.Context/UpsertResource"
	Context_DeleteResource_FullMethodName   = "/engine.Context/DeleteResource"
	Context_SearchContext_FullMethodName    = "/engine.Context/SearchContext"
	Context_SyncWorkspace_FullMethodName    = "/engine.Context/SyncWorkspace"
	Context_ListFiles_FullMethodName        = "/engine.Context/ListFiles"
	Context_ReadFile_FullMethodName         = "/engine.Context/ReadFile"
	Context_WriteFile_FullMethodName        = "/engine.Context/WriteFile"
	Context_DeleteFile_FullMethodName       = "/engine.Context/DeleteFile"
	Context_MoveFile_FullMethodName         = "/engine.Context/MoveFile"
	Context_AppendSession_FullMethodName    = "/engine.Context/AppendSession"
	Context_GetSession_FullMethodName       = "/engine.Context/GetSession"
)

// ContextClient is the client API for Context service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ContextClient interface {
	GetContextStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ContextStatus, error)
	ListResources(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ContextResourceList, error)
	UpsertResource(ctx context.Context, in *ContextUpsertResourceRequest, opts ...grpc.CallOption) (*ContextUpsertResourceResponse, error)
	DeleteResource(ctx context.Context, in *ContextDeleteResourceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SearchContext(ctx context.Context, in *ContextSearchRequest, opts ...grpc.CallOption) (*ContextSearchResponse, error)
	SyncWorkspace(ctx context.Context, in *ContextWorkspaceSyncRequest, opts ...grpc.CallOption) (*ContextWorkspaceSyncResponse, error)
	ListFiles(ctx context.Context, in *ContextFileListRequest, opts ...grpc.CallOption) (*ContextFileListResponse, error)
	ReadFile(ctx context.Context, in *ContextFileReadRequest, opts ...grpc.CallOption) (*ContextFileReadResponse, error)
	WriteFile(ctx context.Context, in *ContextFileWriteRequest, opts ...grpc.CallOption) (*ContextFileWriteResponse, error)
	DeleteFile(ctx context.Context, in *ContextFileDeleteRequest, opts ...grpc.CallOption) (*ContextFileDeleteResponse, error)
	MoveFile(ctx context.Context, in *ContextFileMoveRequest, opts ...grpc.CallOption) (*ContextFileMoveResponse, error)
	AppendSession(ctx context.Context, in *ContextSessionAppendRequest, opts ...grpc.CallOption) (*ContextSessionHistory, error)
	GetSession(ctx context.Context, in *ContextSessionGetRequest, opts ...grpc.CallOption) (*ContextSessionHistory, error)
}

type contextClient struct {
	cc grpc.ClientConnInterface
}

func NewContextClient(cc grpc.ClientConnInterface) ContextClient {
	return &contextClient{cc}
}

func (c *contextClient) GetContextStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ContextStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContextStatus)
	err := c.cc.Invoke(ctx, Context_GetContextStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contextClient) ListResources(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ContextResourceList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContextResourceList)
	err := c.cc.Invoke(ctx, Context_ListResources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contextClient) UpsertResource(ctx context.Context, in *ContextUpsertResourceRequest, opts ...grpc.CallOption) (*ContextUpsertResourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContextUpsertResourceResponse)
	err := c.cc.Invoke(ctx, Context_UpsertResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contextClient) DeleteResource(ctx context.Context, in *ContextDeleteResourceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Context_DeleteResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contextClient) SearchContext(ctx context.Context, in *ContextSearchRequest, opts ...grpc.CallOption) (*ContextSearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContextSearchResponse)
	err := c.cc.Invoke(ctx, Context_SearchContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contextClient) SyncWorkspace(ctx context.Context, in *ContextWorkspaceSyncRequest, opts ...grpc.CallOption) (*ContextWorkspaceSyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContextWorkspaceSyncResponse)
	err := c.cc.Invoke(ctx, Context_SyncWorkspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contextClient) ListFiles(ctx context.Context, in *ContextFileListRequest, opts ...grpc.CallOption) (*ContextFileListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContextFileListResponse)
	err := c.cc.Invoke(ctx, Context_ListFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contextClient) ReadFile(ctx context.Context, in *ContextFileReadRequest, opts ...grpc.CallOption) (*ContextFileReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContextFileReadResponse)
	err := c.cc.Invoke(ctx, Context_ReadFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contextClient) WriteFile(ctx context.Context, in *ContextFileWriteRequest, opts ...grpc.CallOption) (*ContextFileWriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContextFileWriteResponse)
	err := c.cc.Invoke(ctx, Context_WriteFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contextClient) DeleteFile(ctx context.Context, in *ContextFileDeleteRequest, opts ...grpc.CallOption) (*ContextFileDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContextFileDeleteResponse)
	err := c.cc.Invoke(ctx, Context_DeleteFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contextClient) MoveFile(ctx context.Context, in *ContextFileMoveRequest, opts ...grpc.CallOption) (*ContextFileMoveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContextFileMoveResponse)
	err := c.cc.Invoke(ctx, Context_MoveFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contextClient) AppendSession(ctx context.Context, in *ContextSessionAppendRequest, opts ...grpc.CallOption) (*ContextSessionHistory, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContextSessionHistory)
	err := c.cc.Invoke(ctx, Context_AppendSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contextClient) GetSession(ctx context.Context, in *ContextSessionGetRequest, opts ...grpc.CallOption) (*ContextSessionHistory, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContextSessionHistory)
	err := c.cc.Invoke(ctx, Context_GetSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContextServer is the server API for Context service.
// All implementations must embed UnimplementedContextServer
// for forward compatibility.
type ContextServer interface {
	GetContextStatus(context.Context, *emptypb.Empty) (*ContextStatus, error)
	ListResources(context.Context, *emptypb.Empty) (*ContextResourceList, error)
	UpsertResource(context.Context, *ContextUpsertResourceRequest) (*ContextUpsertResourceResponse, error)
	DeleteResource(context.Context, *ContextDeleteResourceRequest) (*emptypb.Empty, error)
	SearchContext(context.Context, *ContextSearchRequest) (*ContextSearchResponse, error)
	SyncWorkspace(context.Context, *ContextWorkspaceSyncRequest) (*ContextWorkspaceSyncResponse, error)
	ListFiles(context.Context, *ContextFileListRequest) (*ContextFileListResponse, error)
	ReadFile(context.Context, *ContextFileReadRequest) (*ContextFileReadResponse, error)
	WriteFile(context.Context, *ContextFileWriteRequest) (*ContextFileWriteResponse, error)
	DeleteFile(context.Context, *ContextFileDeleteRequest) (*ContextFileDeleteResponse, error)
	MoveFile(context.Context, *ContextFileMoveRequest) (*ContextFileMoveResponse, error)
	AppendSession(context.Context, *ContextSessionAppendRequest) (*ContextSessionHistory, error)
	GetSession(context.Context, *ContextSessionGetRequest) (*ContextSessionHistory, error)
	mustEmbedUnimplementedContextServer()
}

// UnimplementedContextServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedContextServer struct{}

func (UnimplementedContextServer) GetContextStatus(context.Context, *emptypb.Empty) (*ContextStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContextStatus not implemented")
}
func (UnimplementedContextServer) ListResources(context.Context, *emptypb.Empty) (*ContextResourceList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListResources not implemented")
}
func (UnimplementedContextServer) UpsertResource(context.Context, *ContextUpsertResourceRequest) (*ContextUpsertResourceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertResource not implemented")
}
func (UnimplementedContextServer) DeleteResource(context.Context, *ContextDeleteResourceRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteResource not implemented")
}
func (UnimplementedContextServer) SearchContext(context.Context, *ContextSearchRequest) (*ContextSearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchContext not implemented")
}
func (UnimplementedContextServer) SyncWorkspace(context.Context, *ContextWorkspaceSyncRequest) (*ContextWorkspaceSyncResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncWorkspace not implemented")
}
func (UnimplementedContextServer) ListFiles(context.Context, *ContextFileListRequest) (*ContextFileListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFiles not implemented")
}
func (UnimplementedContextServer) ReadFile(context.Context, *ContextFileReadRequest) (*ContextFileReadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadFile not implemented")
}
func (UnimplementedContextServer) WriteFile(context.Context, *ContextFileWriteRequest) (*ContextFileWriteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteFile not implemented")
}
func (UnimplementedContextServer) DeleteFile(context.Context, *ContextFileDeleteRequest) (*ContextFileDeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFile not implemented")
}
func (UnimplementedContextServer) MoveFile(context.Context, *ContextFileMoveRequest) (*ContextFileMoveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MoveFile not implemented")
}
func (UnimplementedContextServer) AppendSession(context.Context, *ContextSessionAppendRequest) (*ContextSessionHistory, error) {
	return nil, status.Error(codes.Unimplemented, "method AppendSession not implemented")
}
func (UnimplementedContextServer) GetSession(context.Context, *ContextSessionGetRequest) (*ContextSessionHistory, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSession not implemented")
}
func (UnimplementedContextServer) mustEmbedUnimplementedContextServer() {}
func (UnimplementedContextServer) testEmbeddedByValue()                 {}

// UnsafeContextServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContextServer will
// result in compilation errors.
type UnsafeContextServer interface {
	mustEmbedUnimplementedContextServer()
}

func RegisterContextServer(s grpc.ServiceRegistrar, srv ContextServer) {
	// If the following call panics, it indicates UnimplementedContextServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Context_ServiceDesc, srv)
}

func _Context_GetContextStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContextServer).GetContextStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Context_GetContextStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContextServer).GetContextStatus(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Context_ListResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContextServer).ListResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Context_ListResources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContextServer).ListResources(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Context_UpsertResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContextUpsertResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContextServer).UpsertResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Context_UpsertResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContextServer).UpsertResource(ctx, req.(*ContextUpsertResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Context_DeleteResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContextDeleteResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContextServer).DeleteResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Context_DeleteResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContextServer).DeleteResource(ctx, req.(*ContextDeleteResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Context_SearchContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContextSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContextServer).SearchContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Context_SearchContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContextServer).SearchContext(ctx, req.(*ContextSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Context_SyncWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContextWorkspaceSyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContextServer).SyncWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Context_SyncWorkspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContextServer).SyncWorkspace(ctx, req.(*ContextWorkspaceSyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Context_ListFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContextFileListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContextServer).ListFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Context_ListFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContextServer).ListFiles(ctx, req.(*ContextFileListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Context_ReadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContextFileReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContextServer).ReadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Context_ReadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContextServer).ReadFile(ctx, req.(*ContextFileReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Context_WriteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContextFileWriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContextServer).WriteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Context_WriteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContextServer).WriteFile(ctx, req.(*ContextFileWriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Context_DeleteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContextFileDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContextServer).DeleteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Context_DeleteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContextServer).DeleteFile(ctx, req.(*ContextFileDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Context_MoveFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContextFileMoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContextServer).MoveFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Context_MoveFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContextServer).MoveFile(ctx, req.(*ContextFileMoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Context_AppendSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContextSessionAppendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContextServer).AppendSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Context_AppendSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContextServer).AppendSession(ctx, req.(*ContextSessionAppendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Context_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContextSessionGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContextServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Context_GetSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContextServer).GetSession(ctx, req.(*ContextSessionGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Context_ServiceDesc is the grpc.ServiceDesc for Context service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Context_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "engine.Context",
	HandlerType: (*ContextServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetContextStatus",
			Handler:    _Context_GetContextStatus_Handler,
		},
		{
			MethodName: "ListResources",
			Handler:    _Context_ListResources_Handler,
		},
		{
			MethodName: "UpsertResource",
			Handler:    _Context_UpsertResource_Handler,
		},
		{
			MethodName: "DeleteResource",
			Handler:    _Context_DeleteResource_Handler,
		},
		{
			MethodName: "SearchContext",
			Handler:    _Context_SearchContext_Handler,
		},
		{
			MethodName: "SyncWorkspace",
			Handler:    _Context_SyncWorkspace_Handler,
		},
		{
			MethodName: "ListFiles",
			Handler:    _Context_ListFiles_Handler,
		},
		{
			MethodName: "ReadFile",
			Handler:    _Context_ReadFile_Handler,
		},
		{
			MethodName: "WriteFile",
			Handler:    _Context_WriteFile_Handler,
		},
		{
			MethodName: "DeleteFile",
			Handler:    _Context_DeleteFile_Handler,
		},
		{
			MethodName: "MoveFile",
			Handler:    _Context_MoveFile_Handler,
		},
		{
			MethodName: "AppendSession",
			Handler:    _Context_AppendSession_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _Context_GetSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "engine.proto",
}

const (
	Training_StartRun_FullMethodName      = "/engine.Training/StartRun"
	Training_CancelRun_FullMethodName     = "/engine.Training/CancelRun"
	Training_ListRuns_FullMethodName      = "/engine.Training/ListRuns"
	Training_ListArtifacts_FullMethodName = "/engine.Training/ListArtifacts"
	Training_StreamLogs_FullMethodName    = "/engine.Training/StreamLogs"
)

// TrainingClient is the client API for Training service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrainingClient interface {
	StartRun(ctx context.Context, in *TrainingRunRequest, opts ...grpc.CallOption) (*TrainingRun, error)
	CancelRun(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListRuns(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TrainingRunList, error)
	ListArtifacts(ctx context.Context, in *ArtifactsRequest, opts ...grpc.CallOption) (*ArtifactList, error)
	StreamLogs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TrainingLog], error)
}

type trainingClient struct {
	cc grpc.ClientConnInterface
}

func NewTrainingClient(cc grpc.ClientConnInterface) TrainingClient {
	return &trainingClient{cc}
}

func (c *trainingClient) StartRun(ctx context.Context, in *TrainingRunRequest, opts ...grpc.CallOption) (*TrainingRun, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrainingRun)
	err := c.cc.Invoke(ctx, Training_StartRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trainingClient) CancelRun(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Training_CancelRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trainingClient) ListRuns(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TrainingRunList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrainingRunList)
	err := c.cc.Invoke(ctx, Training_ListRuns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trainingClient) ListArtifacts(ctx context.Context, in *ArtifactsRequest, opts ...grpc.CallOption) (*ArtifactList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArtifactList)
	err := c.cc.Invoke(ctx, Training_ListArtifacts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trainingClient) StreamLogs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TrainingLog], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Training_ServiceDesc.Streams[0], Training_StreamLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogsRequest, TrainingLog]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Training_StreamLogsClient = grpc.ServerStreamingClient[TrainingLog]

// TrainingServer is the server API for Training service.
// All implementations must embed UnimplementedTrainingServer
// for forward compatibility.
type TrainingServer interface {
	StartRun(context.Context, *TrainingRunRequest) (*TrainingRun, error)
	CancelRun(context.Context, *CancelRequest) (*emptypb.Empty, error)
	ListRuns(context.Context, *emptypb.Empty) (*TrainingRunList, error)
	ListArtifacts(context.Context, *ArtifactsRequest) (*ArtifactList, error)
	StreamLogs(*LogsRequest, grpc.ServerStreamingServer[TrainingLog]) error
	mustEmbedUnimplementedTrainingServer()
}

// UnimplementedTrainingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrainingServer struct{}

func (UnimplementedTrainingServer) StartRun(context.Context, *TrainingRunRequest) (*TrainingRun, error) {
	return nil, status.Error(codes.Unimplemented, "method StartRun not implemented")
}
func (UnimplementedTrainingServer) CancelRun(context.Context, *CancelRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelRun not implemented")
}
func (UnimplementedTrainingServer) ListRuns(context.Context, *emptypb.Empty) (*TrainingRunList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRuns not implemented")
}
func (UnimplementedTrainingServer) ListArtifacts(context.Context, *ArtifactsRequest) (*ArtifactList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListArtifacts not implemented")
}
func (UnimplementedTrainingServer) StreamLogs(*LogsRequest, grpc.ServerStreamingServer[TrainingLog]) error {
	return status.Error(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedTrainingServer) mustEmbedUnimplementedTrainingServer() {}
func (UnimplementedTrainingServer) testEmbeddedByValue()                  {}

// UnsafeTrainingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrainingServer will
// result in compilation errors.
type UnsafeTrainingServer interface {
	mustEmbedUnimplementedTrainingServer()
}

func RegisterTrainingServer(s grpc.ServiceRegistrar, srv TrainingServer) {
	// If the following call panics, it indicates UnimplementedTrainingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Training_ServiceDesc, srv)
}

func _Training_StartRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrainingRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainingServer).StartRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Training_StartRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainingServer).StartRun(ctx, req.(*TrainingRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Training_CancelRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainingServer).CancelRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Training_CancelRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainingServer).CancelRun(ctx, req.(*CancelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Training_ListRuns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainingServer).ListRuns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Training_ListRuns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainingServer).ListRuns(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Training_ListArtifacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArtifactsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainingServer).ListArtifacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Training_ListArtifacts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainingServer).ListArtifacts(ctx, req.(*ArtifactsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Training_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TrainingServer).StreamLogs(m, &grpc.GenericServerStream[LogsRequest, TrainingLog]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Training_StreamLogsServer = grpc.ServerStreamingServer[TrainingLog]

// Training_ServiceDesc is the grpc.ServiceDesc for Training service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Training_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "engine.Training",
	HandlerType: (*TrainingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartRun",
			Handler:    _Training_StartRun_Handler,
		},
		{
			MethodName: "CancelRun",
			Handler:    _Training_CancelRun_Handler,
		},
		{
			MethodName: "ListRuns",
			Handler:    _Training_ListRuns_Handler,
		},
		{
			MethodName: "ListArtifacts",
			Handler:    _Training_ListArtifacts_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamLogs",
			Handler:       _Training_StreamLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "engine.proto",
}

const (
	MCP_Connect_FullMethodName    = "/engine.MCP/Connect"
	MCP_Disconnect_FullMethodName = "/engine.MCP/Disconnect"
	MCP_ListTools_FullMethodName  = "/engine.MCP/ListTools"
	MCP_CallTool_FullMethodName   = "/engine.MCP/CallTool"
)

// MCPClient is the client API for MCP service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MCPClient interface {
	Connect(ctx context.Context, in *MCPConnectionRequest, opts ...grpc.CallOption) (*MCPConnection, error)
	Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListTools(ctx context.Context, in *MCPConnectionRequest, opts ...grpc.CallOption) (*ToolList, error)
	CallTool(ctx context.Context, in *CallToolRequest, opts ...grpc.CallOption) (*CallToolResponse, error)
}

type mCPClient struct {
	cc grpc.ClientConnInterface
}

func NewMCPClient(cc grpc.ClientConnInterface) MCPClient {
	return &mCPClient{cc}
}

func (c *mCPClient) Connect(ctx context.Context, in *MCPConnectionRequest, opts ...grpc.CallOption) (*MCPConnection, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MCPConnection)
	err := c.cc.Invoke(ctx, MCP_Connect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCPClient) Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MCP_Disconnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCPClient) ListTools(ctx context.Context, in *MCPConnectionRequest, opts ...grpc.CallOption) (*ToolList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ToolList)
	err := c.cc.Invoke(ctx, MCP_ListTools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCPClient) CallTool(ctx context.Context, in *CallToolRequest, opts ...grpc.CallOption) (*CallToolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallToolResponse)
	err := c.cc.Invoke(ctx, MCP_CallTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MCPServer is the server API for MCP service.
// All implementations must embed UnimplementedMCPServer
// for forward compatibility.
type MCPServer interface {
	Connect(context.Context, *MCPConnectionRequest) (*MCPConnection, error)
	Disconnect(context.Context, *DisconnectRequest) (*emptypb.Empty, error)
	ListTools(context.Context, *MCPConnectionRequest) (*ToolList, error)
	CallTool(context.Context, *CallToolRequest) (*CallToolResponse, error)
	mustEmbedUnimplementedMCPServer()
}

// UnimplementedMCPServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMCPServer struct{}

func (UnimplementedMCPServer) Connect(context.Context, *MCPConnectionRequest) (*MCPConnection, error) {
	return nil, status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedMCPServer) Disconnect(context.Context, *DisconnectRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Disconnect not implemented")
}
func (UnimplementedMCPServer) ListTools(context.Context, *MCPConnectionRequest) (*ToolList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTools not implemented")
}
func (UnimplementedMCPServer) CallTool(context.Context, *CallToolRequest) (*CallToolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CallTool not implemented")
}
func (UnimplementedMCPServer) mustEmbedUnimplementedMCPServer() {}
func (UnimplementedMCPServer) testEmbeddedByValue()             {}

// UnsafeMCPServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MCPServer will
// result in compilation errors.
type UnsafeMCPServer interface {
	mustEmbedUnimplementedMCPServer()
}

func RegisterMCPServer(s grpc.ServiceRegistrar, srv MCPServer) {
	// If the following call panics, it indicates UnimplementedMCPServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MCP_ServiceDesc, srv)
}

func _MCP_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MCPConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCP_Connect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPServer).Connect(ctx, req.(*MCPConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCP_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCP_Disconnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPServer).Disconnect(ctx, req.(*DisconnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCP_ListTools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MCPConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPServer).ListTools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCP_ListTools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPServer).ListTools(ctx, req.(*MCPConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCP_CallTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPServer).CallTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCP_CallTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPServer).CallTool(ctx, req.(*CallToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MCP_ServiceDesc is the grpc.ServiceDesc for MCP service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MCP_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "engine.MCP",
	HandlerType: (*MCPServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Connect",
			Handler:    _MCP_Connect_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _MCP_Disconnect_Handler,
		},
		{
			MethodName: "ListTools",
			Handler:    _MCP_ListTools_Handler,
		},
		{
			MethodName: "CallTool",
			Handler:    _MCP_CallTool_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "engine.proto",
}
